# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'Workshop 2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workshop 2018
  pod 'Swinject', '~> 2.4.0'
  
  pod 'MJSwiftCore'
  pod 'MJSwiftCore/Alamofire'
  pod 'MJSwiftCore/Realm'
  pod 'MJSwiftCore/Vastra'
  pod 'MJSwiftCore/iOS'
  
  target 'Workshop 2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Workshop 2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
